layouts:
  - fullscreen
  - two-pane

mouse-follows-focus: false

mod1:
  - control
  - command

mod3:
  - option

focus-ccw:
  mod: mod3
  key: j
focus-cw:
  mod: mod3
  key: k
swap-screen-ccw:
  mod: mod1
  key: j
swap-screen-cw:
  mod: mod1
  key: k
throw-screen-1:
  mod: mod1
  key: "1"
throw-screen-2:
  mod: mod1
  key: "2"
throw-screen-3:
  mod: mod1
  key: "3"
focus-screen-1:
  mod: mod1
  key: w
focus-screen-2:
  mod: mod1
  key: e
focus-screen-3:
  mod: mod1
  key: r
select-fullscreen-layout:
  mod: mod1
  key: f
select-two-pane-layout:
  mod: mod1
  key: a
select-tall-layout:
  mod: mod1
  key: s
