require("app-launcher")
require("zk")
require("vocabulary")
require("music")
require("source-switcher")
require("source-replacer")
require("screenshot")

hs.hotkey.bind({ "cmd", "ctrl" }, "R", function()
	hs.reload()
end)
hs.alert.show("Config loaded")
